# Generated by Django 6.0.5 on 2026-06-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
