# Generated by Django 6.0.5 on 2026-06-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_alter_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
