# Generated by Django 6.0.5 on 2026-06-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0006_remove_job_category_delete_jobcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
    ]
