# Generated by Django 6.0.5 on 2026-06-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0009_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
