# Generated by Django 6.0.5 on 2026-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0010_remove_job_job_description_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
