# Generated by Django 6.0.5 on 2026-06-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0014_remove_job_recruiter_userprofile_delete_recruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
